{% set name = "pysbol3" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SynBioDex/pySBOL3/archive/v{{ version }}.tar.gz
  sha256: bdb0895d610211ed48b199ffdcc0ae6be0fd0a226dd0a56621550a38504bb2f9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - rdflib >=6.1.1
    - python-dateutil ~=2.8.2
    - pyshacl ~=0.18.1

test:
  source_files:
    - test
    - examples
  imports:
    - sbol3
  requires:
    - pytest
    - git
  commands:
    - git clone --recurse-submodules https://github.com/SynBioDex/pySBOL3.git && cp -r pySBOL3/test/SBOLTestSuite test/.
    - pytest -v test

about:
  home: https://github.com/SynBioDex/pySBOL3
  summary: Pure Python implementation of SBOL 3 standard
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kenza12
    - breakthewall
    - tduigou
