{% set name = "pysbol3" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SynBioDex/pySBOL3/archive/v{{ version }}.tar.gz
  sha256: e13e607f91e7f24d8a20067cf15f5ef9b1af701a978d7015571d75d9c16396aa

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - rdflib >=6.1.1
    - python-dateutil ~=2.8.2
    - pyshacl ~=0.18.1

test:
  source_files:
    - test
    - examples
  imports:
    - sbol3
  requires:
    - pytest
    - git
    - python {{ python_min }}
  commands:
    - git clone --recurse-submodules https://github.com/SynBioDex/pySBOL3.git && cp -r pySBOL3/test/SBOLTestSuite test/.
    - pytest -v test

about:
  home: https://github.com/SynBioDex/pySBOL3
  summary: Pure Python implementation of SBOL 3 standard
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kenza12
    - breakthewall
    - tduigou
